WARNING:tensorflow:From /home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
tf_dict 0.008837461471557617
Tensor("Exp:0", shape=(), dtype=float64)
Tensor("Exp_1:0", shape=(), dtype=float64)
Tensor("Exp_2:0", shape=(), dtype=float64)
Tensor("Exp_3:0", shape=(), dtype=float64)
Tensor("Exp_4:0", shape=(), dtype=float64)
graph 2.4578604698181152
var init 0.7433013916015625
Traceback (most recent call last):
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'therm_0_xi_place' with dtype double
	 [[{{node therm_0_xi_place}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nano_init.py", line 104, in <module>
    start_sim(config, args)
  File "nano_init.py", line 77, in start_sim
    md.run_md_sim(simul_box, thermos, ion_dict, charge_meshpoint, valency_counterion, mdremote)
  File "/extra/alfuerst/repos/tensorflow-simulations/tf/nano/md.py", line 78, in run_md_sim
    loop(simul_box, thermostats_g, ion_dict_g, bin_density_g, ion_dict, tf_ion_place, thermostats, sess, mdremote.steps, expfac_real)
  File "/extra/alfuerst/repos/tensorflow-simulations/tf/nano/md.py", line 48, in loop
    therms_out, ion_dict_out, (pos_bin_density, neg_bin_density), expfac_real = session.run([thermo_g, ion_g, bin_density_g, expfac_real], feed_dict=feed)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'therm_0_xi_place' with dtype double
	 [[node therm_0_xi_place (defined at /home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'therm_0_xi_place':
  File "nano_init.py", line 104, in <module>
    start_sim(config, args)
  File "nano_init.py", line 72, in start_sim
    thermos = thermostat.make_thremostats(chain_length_real=5, ions_count=len(ion_dict[interface.ion_pos_str]))
  File "/extra/alfuerst/repos/tensorflow-simulations/tf/nano/thermostat.py", line 62, in make_thremostats
    therms.append(Thremostat(i, Q, utility.T, 3* ions_count, 0.0, 0.0, 0.0))
  File "/extra/alfuerst/repos/tensorflow-simulations/tf/nano/thermostat.py", line 21, in __init__
    self.xi_place=tf.compat.v1.placeholder(dtype=common.tf_dtype, name=self.n+"xi_place", shape=scalar_shape)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2619, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6669, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/alfuerst/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

